### PR TITLE
telegram.sh: set $TMPDIR to a readable path

### PR DESCRIPTION
**Pull request by 3v1n0**
Fixes issue #2

### CODE REVIEW

**Comment by sergiusens** [comment]
Does this make it work? Tried your previous commit and it didn't do much (sorry, forgot to reply about it)

**Comment by 3v1n0** [comment]
Actually..... It might not be enough, as it would probably need [this patch](https://codereview.qt-project.org/#/c/182564/3/src/platformsupport/themes/genericunix/dbustray/qdbustrayicon.cpp) too... Mhmm

**Comment by sergiusens** [comment]
Maybe propose it to the desktop telegram folks, they already do some patching themselves

**Comment by 3v1n0** [comment]
Yeah, I've already it in my [telegram-snap](https://github.com/3v1n0/telegram-snap/blob/master/patches/qtbase_5_6_2.diff) repo, I've just to clean some things up before proposing

**Comment by 3v1n0** [comment]
I've actually sent upstream a patch to make them use libappindicator instead, thus this should not be needed at all... The indicator in new versions should just work.

**Pull request closed without merging**
